//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour
    {
        public int HoursID { get; set; }
        public int RequirementID { get; set; }
        public int PhaseID { get; set; }
        public double Hours { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
