//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Members = new HashSet<Member>();
            this.Risks = new HashSet<Risk>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Description { get; set; }
        public string ProjectName { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual User User { get; set; }
        public virtual Requirement Requirement { get; set; }
        public virtual ICollection<Risk> Risks { get; set; }
    }
}
