//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.Hours = new HashSet<Hour>();
        }
    
        public int RequirementID { get; set; }
        public int ProjectID { get; set; }
        public string RequirementType { get; set; }
        public string Description { get; set; }
        public string Number { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Hour> Hours { get; set; }
    }
}
