//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskLevel
    {
        public RiskLevel()
        {
            this.Risks = new HashSet<Risk>();
        }
    
        public int RiskLevelID { get; set; }
        public string LevelName { get; set; }
    
        public virtual ICollection<Risk> Risks { get; set; }
    }
}
