//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskStatus
    {
        public RiskStatus()
        {
            this.Risk = new HashSet<Risk>();
        }
    
        public int RiskStatusID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Risk> Risk { get; set; }
    }
}
