//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public int RiskID { get; set; }
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RiskLevelID { get; set; }
        public int RiskStatusID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual RiskLevel RiskLevel { get; set; }
        public virtual RiskStatus RiskStatus { get; set; }
    }
}
